<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>rq</string>
		<string>sparql</string>
	</array>
	<key>name</key>
	<string>SPARQL</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Keywords</string>
			<key>match</key>
			<string>\b(?i:base|prefix|define|select|distinct|reduced|from|named|construct|ask|describe|where|graph|bind|as|filter|optional|union|order|by|group|limit|offset|values|insert data|delete data|with|delete|insert|clear|silent|default|all|create|drop|copy|move|add|to|using|service|not exists|exists|not in|in|minus)\b</string>
			<key>name</key>
			<string>keyword.sparql</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>SPARQL built-in functions</string>
			<key>match</key>
			<string>\b(?i:concat|regex|asc|desc|bound|isiri|isuri|isblank|isliteral|str|lang|datatype|sameterm|langmatches|avg|count|group_concat|separator|max|min|sample|sum|iri|bnode|strdt|uuid|struuid|strlen|strlen|strlen|substr|ucase|lcase|strstarts|strends|contains|strbefore|strafter|encode_for_uri|replace|abs|round|ceil|floor|rand|now|year|month|day|hours|minutes|seconds|timezone|tz|md5|sha1|sha256|sha384|sha512|coalesce|if)\b</string>
			<key>name</key>
			<string>support.function.sparql</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>URI</string>
			<key>match</key>
			<string>&lt;[^&lt;&gt;"{}|^`\]\\]*&gt;</string>
			<key>name</key>
			<string>string.uri.sparql</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.other.sparql</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.sparql</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Prefix / prefixed URI</string>
			<key>match</key>
			<string>(\w*:)([^\s|/^*?+{}()]*)</string>
			<key>name</key>
			<string>constant.complex.sparql</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>The special triple predicate 'a'</string>
			<key>match</key>
			<string>\sa\s</string>
			<key>name</key>
			<string>entity.name.class.rdfs-type.sparql</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;!\w)[?$]\w+</string>
			<key>name</key>
			<string>variable.other.sparql</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.sparql</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.sparql</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.type.sparql</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Typed literal</string>
			<key>match</key>
			<string>("[^"]*")(\^\^)(&lt;[^&lt;&gt;"{}|^`\]\\]*&gt;|\w*:[^\s)]+)</string>
			<key>name</key>
			<string>literal.sparql</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.sparql</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.sparql</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.type.sparql</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>String literal</string>
			<key>match</key>
			<string>('''(?:(?:'|'')?(?:[^'\\]|\\[tbnrf\"']))*'''|"""(?:(?:"|"")?([^"\\]|\\[tbnrf\"']))*"""|'(?:(?:[^\x22\x5C\xA\xD])|\\[tbnrf\"'])*'|"(?:(?:[^\x22\x5C\xA\xD])|\\[tbnrf\"'])*"|'''.*'''|'[^']*')(@[a-zA-Z-]+)?</string>
			<key>name</key>
			<string>string.sparql</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.sparql</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.sparql</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\{\s*(\d+)?(\s*(?:,\s*(\d+)?)?)+\s*\}</string>
			<key>name</key>
			<string>keyword.operator.range.complex.sparql</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Numeric literal</string>
			<key>match</key>
			<string>\b[+-]?(?:\d+|[0-9]+\.[0-9]*|\.[0-9]+(?:[eE][+-]?\d+)?)\b</string>
			<key>name</key>
			<string>constant.numeric.sparql</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Boolean</string>
			<key>match</key>
			<string>\b(?i:true|false)\b</string>
			<key>name</key>
			<string>constant.language.sparql</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>SPARQL operators</string>
			<key>match</key>
			<string>(?:\|\||&amp;&amp;|=|!=|&lt;|&gt;|&lt;=|&gt;=|\*|/|\+|-|\||\^|\?|\!)</string>
			<key>name</key>
			<string>keyword.operator.sparql</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Comments</string>
			<key>match</key>
			<string>#.*$</string>
			<key>name</key>
			<string>comment.line.number-sign.sparql</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.sparql</string>
</dict>
</plist>
