version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9-stretch
    steps:
      - checkout
      - restore_cache:
          # This caching strategy isn't ideal, but CircleCI's current support for monorepos is poor, and this works well enough
          keys:
          # This branch if available
          - dependency-cache-{{ .Branch }}-{{ checksum "./vscode-langserver-sms/yarn.lock" }}-{{ checksum "./vscode-langserver-sparql/yarn.lock" }}-{{ checksum "./vscode-langserver-turtle/yarn.lock" }}
          # Default branch if not
          - dependency-cache-develop-{{ checksum "./vscode-langserver-sms/yarn.lock" }}-{{ checksum "./vscode-langserver-sparql/yarn.lock" }}-{{ checksum "./vscode-langserver-turtle/yarn.lock" }}
      - run:
          name: Install Node Modules
          command: |
            pushd ./vscode-langserver-sms && yarn && popd
            pushd ./vscode-langserver-sparql && yarn && popd
            pushd ./vscode-langserver-turtle && yarn && popd
      - save_cache:
          key: dependency-cache-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ checksum "./vscode-langserver-sms/yarn.lock" }}-{{ checksum "./vscode-langserver-sparql/yarn.lock" }}-{{ checksum "./vscode-langserver-turtle/yarn.lock" }}
          paths:
          - ./vscode-langserver-sms/node_modules
          - ./vscode-langserver-sparql/node_modules
          - ./vscode-langserver-turtle/node_modules
      - persist_to_workspace:
          root: .
          paths:
            - ./

  test:
    docker:
      - image: circleci/node:8.9-stretch
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install OS-level Test Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y libgtk-3-0 libxss1 --no-install-recommends
      - run:
          name: Tests
          command: |
            pushd ./vscode-langserver-sms && yarn test && popd
            pushd ./vscode-langserver-sparql && yarn test && popd
            pushd ./vscode-langserver-turtle && yarn test && popd
  
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
